name: Deploy to Linux Server via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application via FTP
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up an FTP client to upload files
    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deployment/ # Specify the directory to deploy
        server-dir: /domains/lesedingconsulting.co.za/public_html/lcsnew/ # Specify the target directory on the server